config/routes.rb
Rails.application.routes.draw do
  root to: "pages#home"

  # get 'senior_leadership', to: 'pages#senior_leadership'
  # get 'neighbourhood_policing', to: 'pages#neighbourhood_policing'
  # get 'crime_data', to: 'pages#crime_data'

  resources :forces, only: [:index, :show]
  # resources :neighbourhoods, only: [:index, :show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/force.rb
class Force < ApplicationRecord
  has_many :neighbourhoods

  validates :api_id, presence: true
  validates :name, presence: true
end

app/models/neighbourhood.rb
class Neighbourhood < ApplicationRecord
  belongs_to :force

  validates :api_id, presence: true
  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/forces_controller.rb
class ForcesController < ApplicationController

  def index
    @forces = Force.all.each do |f|
      if f.description.length > 250
        f.description = f.description.chars.each_slice(250).map(&:join)[0] + "..."
      end
    end
  end

  def show
    @force = Force.find(params[:id])

    @neighbourhoods = @force.neighbourhoods
  end
end

app/controllers/neighbourhoods_controller.rb
class NeighbourhoodsController < ApplicationController
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @category_array = [
      {
        url_path: 'senior_leadership',
        image_path: "senior_police",
        description: "Find out about Senior Leadership in your area",
        button: "Find out more"
      },
      {
        url_path: 'neighbourhood_policing',
        image_path: "neighbourhood_policing",
        description: "Get to know your local officers",
        button: "Find out more"
      },
      {
        url_path: 'crime_data',
        image_path: "crime_data",
        description: "Discover local crime statistics",
        button: "Find out more"
      },
    ]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/forces/_force_list_item.html.erb
<div class="list-item">
  <div class="list-item-photo">
    <%= image_tag "police_badge_placeholder" %>
  </div>
  <%= link_to force_path(force) do %>
    <div class="list-item-details">

      <h2><%= force.name %></h2>
      <p><%= force.description %></p>
    </div>
      <% end %>
  <div class="list-item-contact">
    <p><i class="fa-solid fa-phone"></i> <%= force.telephone %></p>
    <p><i class="fa-brands fa-internet-explorer"></i> <%= link_to "Website", force.url, target: "_blank" %></p>
  </div>
</div>

app/views/forces/index.html.erb
<div class="wrapper">
  <div class="container text-center padded">
    <div class="title">
      <h2>Find your local police force</h2>
    </div>
    <div class="search-bar padded">
      <form action="get" class="inline">
        <input type="text" placeholder="Enter your local police force">
        <input type="submit">
      </form>
    </div>
    <div class="list">
      <% @forces.each do |force| %>
        <%= render 'force_list_item', force: force %>
      <% end %>
    </div>
  </div>
</div>

app/views/forces/show.html.erb
<div class="wrapper">
  <div class="container text-center padded">
    <h1><%= @force.name %></h1>
  </div>
  <%= link_to "All forces", forces_path %>
  <% @neighbourhoods.each do |neighbourhood| %>
    <p><%= neighbourhood.name %></p>
    <br>

  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>JhubPoliceApi</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://api.mapbox.com/mapbox-gl-js/v2.11.0/mapbox-gl.css" rel="stylesheet">
    <script src="https://api.mapbox.com/mapbox-gl-js/v2.11.0/mapbox-gl.js"></script>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= yield %>
    <%= render 'shared/footer' %>
  </body>
</html>

app/views/pages/_card-category.html.erb
<%= link_to url_path do %>
  <div class="card-category">
    <%= image_tag "#{image_path}", class: "card-photo" %>
    <p class="card-category-description"><%= description %> </p>
  </div>
<% end %>

app/views/pages/home.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0, 0, 0, 0.79)), url('<%= image_path "police_background_photo.jpeg" %>');">
  <div class="banner-content">
    <h1>Police Transparency</h1>
    <p>Find information about your local police force easily</p>
    <%= link_to "Find your local police force", forces_path, class: "btn btn-primary banner-cta" %>
  </div>
</div>
<div class="card-wrapper">
  <div class="card-grid">
    <% @category_array.each do |data, null| %>
      <%= render 'card-category', url_path: data[:url_path], image_path: data[:image_path], description: data[:description], button: data[:button] %>
    <% end %>
  </div>
</div>